language: python

python:
  - 2.6
  - 2.7

branches:
  only:
    - master

os:
  - linux
  - osx

before_install:
  - sudo apt-get install libssl-dev
  - sudo apt-get install liblua5.1-dev

script: 
  - python setup.py build